### ISSUE TITLE
Using STRUMPACK on GPUs via PETSc

### ISSUE THREAD

**Issue by s-sajid-ali** [pghysels/STRUMPACK#51]
Hi STRUMPACK-devs, 

I'd like to use STRUMPACK on GPUs via the PETSc interface. However, when I pass GPU-native matrices/vectors (either as CUDA-specific data types or as Kokkos data types whose default exec space is CUDA), the routine `set_csr_matrix` crashes, similar to the crash described in https://github.com/pghysels/STRUMPACK/issues/50. 

How do I pass matrices/vectors that already reside on the GPU to STRUMPACK via the PETSc interface? 

I'd like to add that I was however, able to use GPUs when running the same program with CPU-native datatypes and letting STRUMPACK offload them to the GPU. However, this method of operation was quite slow when compared to other direct solvers like superlu-dist. The code for the problem is [here](https://controlc.com/2ec55bb0) (3D-poisson on a grid size of 64^3, averaged over 5 solves after a warm-up solve where the factorization is computed). Here are the detailed log files (available as links from the timing numbers) from both cases (run on a pair of QuadroP4000s), should that help: 

|            Solver             | Matrix/Vector types  |   Time, 1 GPU | Time, 2 GPUs  |
| ----------------------- | ---------------------- | --------------- | --------------- |
| STRUMPACK-offload |  aij, standard             |   [1.6589e+01](https://controlc.com/9ab46ec9) |   [1.3489e+01](https://controlc.com/8e403b13)   |
| Superlu-dist               | aij-cusparse, cuda     |  [5.6872e+00](https://controlc.com/5f439a24)  |   [4.9308e+00](https://controlc.com/02d81a79)  |   
| Superlu-dist               |  aij-kokkos, kokkos   |   [5.7394e+00](https://controlc.com/4a4d727b)  | [3.7963e+00](https://controlc.com/422814bd)    |

**Comment by pghysels** [comment]
> How do I pass matrices/vectors that already reside on the GPU to STRUMPACK via the PETSc interface?

STRUMPACK does not support this at the moment.
I don't think superlu-dist supports this either, so I will check how this is handled in the PETSc interface to superlu-dist. 

What version of STRUMPACK did you use? Later versions should perform better. 
Is it possible for you to try this with the STRUMPACK master branch, and with this updated interface:
https://gitlab.com/petsc/petsc/-/merge_requests/4543
(I will try this myself with the kokkos and cuda matrices/vectors)

Thank you for reporting all these issue, I'm looking into it.

**Comment by s-sajid-ali** [comment]
>What version of STRUMPACK did you use? 
I used the 6.1.0 release (as it was the latest release provided by spack). 

>Is it possible for you to try this with the STRUMPACK master branch
I'm getting build errors for this. Here is the relevant [cmake-log](https://controlc.com/0913dc7c) and the [spack-log](https://controlc.com/ec7f7e8b)

**Comment by s-sajid-ali** [comment]
New build failure with `butterflypack@2.1.0`, [cmake-log](https://controlc.com/9e39ac10), [spack-log](https://controlc.com/f0d704c9).

**Comment by pghysels** [comment]
STRUMPACK master needs a newer version of butterflypack. You can disable this ~butterflypack.

I'm checking the other errors.

**Comment by pghysels** [comment]
Can you paste your command line options for this test?
How did you select the aijcusparse format?

**Comment by pghysels** [comment]
I reproduced the problem. It's working with aijcusparse and superlu_dist, but not with strumpack.
I'm looking into it.

**Comment by s-sajid-ali** [comment]
Left a comment on the reason behind the crash on the PETSc merge request. Any idea on what is causing the build for the updated branch to fail?

**Comment by pghysels** [comment]
I just managed to replicate this error
```
/tmp/sajid/spack-stage/spack-stage-strumpack-master-htxhlredprikgcrl3qsc7z6tn7nxlmi3/spack-src/src/sparse/fronts/FrontalMatrixGPU.cpp:91:19: error: found ':' in nested-name-specifier, expected '::'
       for (auto F : f) {
```
with g++ 8.5.0.
It works fine with g++ 9.4.0, 10.3.0, and 11.2.0.
I will try to fix it for 8.5.0.

**Comment by pghysels** [comment]
> Left a comment on the reason behind the crash on the PETSc merge request. 

Awesome job figuring out the PETSc issue. I know all the casting with void* is not ideal.
I will try the same approach as in the SuperLU-Dist interface.

**Comment by pghysels** [comment]
> Any idea on what is causing the build for the updated branch to fail?

I pushed a fix for that error:
https://github.com/pghysels/STRUMPACK/commit/b97b01d57d036c0dddfa1372a5818f80760f35ad

**Comment by s-sajid-ali** [comment]
Thanks a lot for the fix!

I re-ran the same problem as above (3d-poisson, scaled; mesh size : `64x64x64` ; 2xP4000 GPUs, no NV-Link.) and saw better times with the updated interface. This problem size is probably still too small for a meaningful comparison. 

```
--------------------------------------------------
    Solver   |    Mat/Vec type    | 1 GPU | 2 GPU
--------------------------------------------------
***************** LU fact ************************
 Strumpack   |     aij/standard   | 1.183 | 0.986 
SuperLU-dist |     aij/standard   | 5.876 | 3.898 
***************** ILU fact ***********************
  cusparse   |  aijcusparse/cuda  | 0.068 |  N/A
************* GMRES + multigrid ******************
    GAMG     |  aijcusparse/cuda  | 0.874 |  0.653
    hypre    |  aijcusparse/cuda  | 0.375 |  0.290
```

**Comment by pghysels** [comment]
Hi Sajid, thanks for the update.

Did you try the new interface, including this fix https://gitlab.com/pghysels/petsc/-/pipelines/460554103 with aijcusparse/cuda?
Did you build STRUMPACK with support for SLATE? This is required to get good multi-GPU performance (make sure to use 1 MPI rank per GPU in this case).

I am making a new STRUMPACK release now and will update the PETSc interface and the SPACK installation script.
Then I still need to verify that the PETSc tests all pass.

**Comment by s-sajid-ali** [comment]
>Did you try the new interface, including this fix https://gitlab.com/pghysels/petsc/-/pipelines/460554103 with aijcusparse/cuda?

No. While the most recent commit fixes the crash with aijcusparse/cuda, it otherwise offers identical performance to using aij/standard types, right? 

>Did you build STRUMPACK with support for SLATE? This is required to get good multi-GPU performance (make sure to use 1 
MPI rank per GPU in this case).

I built everything with spack, and since the SLATE variant is turned on by default, I used it. And I did use 1 MPI rank per GPU as well. 

Once the initial factorization is done on the matrix from CPU memory (with GPU offloading), is it possible to have the factored matrices live on the GPU to perform the subsequent sparse triangular solve using the GPU vectors/matrices or do the factored matrix and RHS vector have to reside on the CPU memory ?

I read some old discussion on the PETSc mailing list which explained that the LU factorization and SpTRSV phases are always done by the same (external to PETSc) framework as the format for distributed-memory LU factors is not consistent between different sparse direct solvers. Is this still the case or has there been recent developments that allow for factorization by STRUMPACK followed by say [this SpTRSV package](https://crd.lbl.gov/assets/Uploads/Multi-GPU-SpTRSV-ACDA21-.pdf) developed at LBNL?  

Thanks again!
